# Simple Docker Compose configuration for Whombat
# This is the recommended way to run Whombat with Docker
#
# Usage:
#   1. Copy .env.example to .env and configure your settings
#   2. Run: docker compose -f compose.simple.yaml up
#
# This will start Whombat with:
# - SQLite database (data stored in ./data volume)
# - Audio files from the directory specified in WHOMBAT_AUDIO_DIR
# - Frontend and backend integrated in a single container

services:
  whombat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whombat
    restart: unless-stopped
    ports:
      - "${WHOMBAT_PORT:-5000}:5000"
    volumes:
      # Database and application data
      - whombat-data:/data
      # Audio files - mount your audio directory here
      # Update WHOMBAT_AUDIO_DIR in .env to point to your audio files
      - ${WHOMBAT_AUDIO_DIR:-./audio}:/audio:ro
    environment:
      - WHOMBAT_HOST=0.0.0.0
      - WHOMBAT_PORT=5000
      - WHOMBAT_DOMAIN=${WHOMBAT_DOMAIN:-localhost}
      - WHOMBAT_AUDIO_DIR=/audio
      - WHOMBAT_DB_URL=sqlite+aiosqlite:////data/whombat.db
      - WHOMBAT_DEV=${WHOMBAT_DEV:-false}
      - WHOMBAT_LOG_TO_STDOUT=true
      - WHOMBAT_LOG_TO_FILE=false
      - WHOMBAT_OPEN_ON_STARTUP=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whombat-data:
    name: whombat-data
