# Docker Compose configuration with PostgreSQL
# Use this for production deployments or when you need better performance
#
# Usage:
#   1. Copy .env.example to .env and configure PostgreSQL settings
#   2. Run: docker compose -f compose.postgres.yaml up
#
# This will start:
# - Whombat backend with PostgreSQL database
# - PostgreSQL database server
# - All services connected via private network

services:
  db:
    image: postgres:16-alpine
    container_name: whombat-db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-whombat}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-whombat}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - whombat-private

  whombat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whombat
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${WHOMBAT_PORT:-5000}:5000"
    volumes:
      # Audio files - mount your audio directory here
      - ${WHOMBAT_AUDIO_DIR:-./audio}:/audio:ro
      # Optional: Application data (not needed for PostgreSQL but useful for backups)
      - whombat-data:/data
    environment:
      - WHOMBAT_HOST=0.0.0.0
      - WHOMBAT_PORT=5000
      - WHOMBAT_DOMAIN=${WHOMBAT_DOMAIN:-localhost}
      - WHOMBAT_AUDIO_DIR=/audio
      - WHOMBAT_DB_DIALECT=postgresql
      - WHOMBAT_DB_HOST=db
      - WHOMBAT_DB_PORT=5432
      - WHOMBAT_DB_NAME=${POSTGRES_DB:-whombat}
      - WHOMBAT_DB_USERNAME=${POSTGRES_USER:-postgres}
      - WHOMBAT_DB_PASSWORD=${POSTGRES_PASSWORD:-whombat}
      - WHOMBAT_DEV=${WHOMBAT_DEV:-false}
      - WHOMBAT_LOG_TO_STDOUT=true
      - WHOMBAT_LOG_TO_FILE=false
      - WHOMBAT_OPEN_ON_STARTUP=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - whombat-private

networks:
  whombat-private:
    name: whombat-private

volumes:
  postgres-data:
    name: whombat-postgres-data
  whombat-data:
    name: whombat-data
