"""Common API functions."""

from whombat.api.common.base import BaseAPI
from whombat.api.common.utils import (
    add_feature_to_object,
    add_note_to_object,
    add_tag_to_object,
    create_object,
    create_objects,
    create_objects_without_duplicates,
    delete_object,
    get_count,
    get_object,
    get_objects,
    get_objects_from_query,
    get_or_create_object,
    insert_batched,
    remove_feature_from_object,
    remove_note_from_object,
    remove_tag_from_object,
    select_batched,
    update_feature_on_object,
    update_object,
)
from whombat.api.common.permissions import (  # noqa: F401
    can_delete_annotation_project,
    can_delete_dataset,
    can_edit_annotation_project,
    can_edit_dataset,
    can_manage_restricted_annotation_project,
    can_manage_restricted_dataset,
    can_view_annotation_project,
    can_view_dataset,
    filter_annotation_projects_by_access,
    filter_datasets_by_access,
)

__all__ = [
    "BaseAPI",
    "add_feature_to_object",
    "add_note_to_object",
    "add_tag_to_object",
    "create_object",
    "create_objects",
    "create_objects_without_duplicates",
    "delete_object",
    "get_count",
    "get_object",
    "get_objects",
    "get_objects_from_query",
    "get_or_create_object",
    "insert_batched",
    "remove_feature_from_object",
    "remove_note_from_object",
    "remove_tag_from_object",
    "select_batched",
    "update_feature_on_object",
    "update_object",
    "can_delete_annotation_project",
    "can_delete_dataset",
    "can_edit_annotation_project",
    "can_edit_dataset",
    "can_manage_restricted_annotation_project",
    "can_manage_restricted_dataset",
    "can_view_annotation_project",
    "can_view_dataset",
    "filter_annotation_projects_by_access",
    "filter_datasets_by_access",
]
