[project]
name = "Whombat"
version = "0.1.0"
description = "Audio Annotation Tool"
authors = [
    {name = "Santiago Martinez", email = "santiago.mbal@gmail.com"},
]
dependencies = [
    "fastapi>=0.92.0",
    "uvicorn[standard]>=0.20.0",
    "sqlalchemy[asyncio]>=2.0.7",
    "fastapi-users[sqlalchemy]>=10.4.1",
    "aiosqlite>=0.18.0",
    "alembic>=1.10.2",
    "passlib[bcrypt]>=1.7.4",
    "numpy>=1.24.3",
    "wavio>=0.0.7",
    "shapely>=2.0.1",
    "pydantic[email]>=2.1.1",
    "pydantic-settings>=2.0.2",
]
requires-python = ">=3.11,<3.12"
readme = "README.rst"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"

[tool.black]
line-length = 79

[tool.pyright]
venvPath = "."
venv = ".venv"
include = ["src", "tests"]
verboseOutput = true
useLibraryCodeForTypes = true

[tool.mypy]
mypy_path = ".venv/lib/python3.11/site-packages"

[tool.pydocstyle]
convention = "numpy"

[tool.isort]
profile = "black"

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.2.2",
    "coverage>=7.2.1",
    "black>=23.1.0",
    "pytest-asyncio>=0.21.0",
    "httpx>=0.23.3",
    "tox>=4.7.0",
    "flake8>=6.1.0",
    "pyright>=1.1.320",
]

