name: Build Frontend

on:
  workflow_call:

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install dependencies
        run: |
          cd front
          npm install
      - name: Build app
        run: |
          cd front
          npm build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: front/out
