name: Build Frontend

on:
  workflow_call:

jobs:
  build-user-guide:
    name: Build User Guide

    runs-on: ubuntu-latest

    env:
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install 3.12

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('back/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('back/uv.lock') }}
            uv-${{ runner.os }}

      - name: Install the project dependencies
        run: |
          cd back
          uv sync --all-extras --dev

      - name: Build Guide
        run: |
          cd back
          uv run mkdocs build -d mkdocs-guide.yml -d site

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: user_guide
          path: back/site

      - name: Minimize uv cache
        run: uv cache prune --ci
