name: Build Frontend

on:
  workflow_call:

jobs:
  build-user-guide:
    name: Build User Guide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd back
          pip install -r guide_requirements.txt
      - name: Build Guide
        run: |
          cd back
          mkdocs build -d mkdocs-guide.yml -d site
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: user_guide
          path: back/site
