name: Bundle App

on:
  release:
    types: [published]

jobs:
  build-user-guide:
    uses: mbsantiago/whombat/.github/workflows/build_user_guide.yml@dev

  build-frontend:
    uses: mbsantiago/whombat/.github/workflows/build_frontend.yml@dev

  build-app:
    name: "Bundle App"

    needs: [build-user-guide, build-frontend]

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-11

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Retrieve built frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: back/src/whombat/statics/

      - name: Retrieve built user guide
        uses: actions/download-artifact@v4
        with:
          name: user_guide
          path: back/src/whombat/user_guide/

      - name: Bundle app (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        run: |
          scripts/bundle_windows.ps1
          mkdir dist/
          mv "back/dist/whombat.zip" "dist/whombat-${{ matrix.os }}-${{ github.ref_name }}.zip"

      - name: Bundle app (Linux)
        if: ${{ matrix.os == 'linux-latest' }}
        run: |
          bash scripts/bundle_linux.sh
          mkdir dist/
          mv back/dist/whombat.zip "dist/whombat-${{ matrix.os }}-${{ github.ref_name }}.zip"

      - name: Bundle app (macOS)
        if: ${{ matrix.os == 'macos-11' }}
        run: |
          bash scripts/bundle_macos.sh
          mkdir dist/
          mv back/dist/whombat.zip "dist/whombat-${{ matrix.os }}-${{ github.ref_name }}.zip"

      - name: Upload release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "dist/whombat-${{ matrix.os }}-${{ github.ref_name }}.zip"
