name: Linting
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd back
          pdm install --dev
      - name: Check formatting
        run: |
          cd back
          pdm run black --check src
          pdm run black --check tests
      - name: Check typing
        run: |
          cd back
          pdm run pyright src
      - name: Check for overall code issues
        run: |
          cd back
          pdm run ruff src
