name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install black ruff pyright
      - name: Check formatting
        run: |
          cd back
          black --check src
          black --check tests
      - name: Check typing
        run: |
          cd back
          pyright src
      - name: Check for overall code issues
        run: |
          cd back
          ruff src
